/* 

Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, •
By considering the terms in the Fibonacci sequence whose values do not exceed N, find
the sum of the even-valued terms.
Input Format
First line contains T that denotes the number of test cases. This is followed by T lines,
each containing an integer. N.
Constraints
1 <= T <= 105
10 <= N <= 4 * 1016
Output Format
Print the required answer for each test case.

*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
class Solution {

    static void Main(String[] args) {
        int t = Convert.ToInt32(Console.ReadLine());
        for(int a0 = 0; a0 < t; a0++){
            long n = Convert.ToInt64(Console.ReadLine());
            // Get fibonacci numbers up to n
            List<long> fibs = new List<long>();
            fibs.Add(1);
            fibs.Add(2);
            long next = 0;
            while (next < n) {
                next = fibs[fibs.Count - 1] + fibs[fibs.Count - 2];
                if (next < n) {
                    fibs.Add(next);
                }
            }
            // Sum even numbers
            long sum = 0;
            foreach (long fib in fibs) {
                if (fib % 2 == 0) {
                    sum += fib;
                }
            }
            Console.WriteLine(sum);
            
        }
    }
}